# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: mesheryctl

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- main: ./mesheryctl/main.go
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.Version={{.Version}}
#   ldflags:
#     - -s -w -X mesheryctl/cmd.Build={{.Version}}
  
  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
  goos:
    - darwin
    - linux
    - freebsd
    - windows

  # # GOARCH to build for.
  # # For more info refer to: https://golang.org/doc/install/source#environment
  # # Defaults are 386 and amd64.
  # goarch:
  #   - amd64
  #   - arm
  #   - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
