before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "GITHUB USERNAME"
  - git config --local user.email "GITHUB EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

services:
  - docker

deploy:
  provider: releases
  user: "GITHUB USERNAME"
  password: "GITHUB PASSWORD"
  file: "mesheryctl"
  skip_cleanup: true