apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery-istio
  name: meshery-istio
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery-istio
    spec:
      serviceAccount: meshery
      containers:
      - image: layer5/meshery-istio
        name: meshery-istio
        ports:
        - containerPort: 10000
        resources: {}
      restartPolicy: Always
status: {}
